# Generated by Django 6.0.1 on 2026-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.IntegerField(),
        ),
    ]
