# Generated by Django 6.0.1 on 2026-03-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
