# Generated by Django 6.0.1 on 2026-04-19 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('continent', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('biography', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('places_traveled', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.country')),
            ],
        ),
        migrations.CreateModel(
            name='BucketListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Low'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('must_visit', 'Must Visit'), ('upcoming', 'Upcoming'), ('visited', 'Visited')], default='must_visit', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('booked', 'Booked'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.bucketlistentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
        ),
    ]
