# Generated by Django 6.0.1 on 2026-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_bucketlistentry_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
