# Generated by Django 6.0.1 on 2026-04-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
