# Generated by Django 6.0.1 on 2026-04-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_country_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='project.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('activity', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='project.tripplan')),
            ],
        ),
    ]
