# Generated by Django 6.0.1 on 2026-04-27 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_destinationrating_itineraryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
