# Generated by Django 6.0.1 on 2026-04-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucketlistentry',
            unique_together={('user', 'destination')},
        ),
    ]
